/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/boat-rescue`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-detail`; params?: Router.UnknownInputParams; } | { pathname: `/evacuate`; params?: Router.UnknownInputParams; } | { pathname: `/medical`; params?: Router.UnknownInputParams; } | { pathname: `/offer-help`; params?: Router.UnknownInputParams; } | { pathname: `/shelter`; params?: Router.UnknownInputParams; } | { pathname: `/water-rescue`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-requests` | `/my-requests`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/boat-rescue`; params?: Router.UnknownOutputParams; } | { pathname: `/emergency-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/evacuate`; params?: Router.UnknownOutputParams; } | { pathname: `/medical`; params?: Router.UnknownOutputParams; } | { pathname: `/offer-help`; params?: Router.UnknownOutputParams; } | { pathname: `/shelter`; params?: Router.UnknownOutputParams; } | { pathname: `/water-rescue`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-requests` | `/my-requests`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/boat-rescue${`?${string}` | `#${string}` | ''}` | `/emergency-detail${`?${string}` | `#${string}` | ''}` | `/evacuate${`?${string}` | `#${string}` | ''}` | `/medical${`?${string}` | `#${string}` | ''}` | `/offer-help${`?${string}` | `#${string}` | ''}` | `/shelter${`?${string}` | `#${string}` | ''}` | `/water-rescue${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/community${`?${string}` | `#${string}` | ''}` | `/community${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-requests${`?${string}` | `#${string}` | ''}` | `/my-requests${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/boat-rescue`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-detail`; params?: Router.UnknownInputParams; } | { pathname: `/evacuate`; params?: Router.UnknownInputParams; } | { pathname: `/medical`; params?: Router.UnknownInputParams; } | { pathname: `/offer-help`; params?: Router.UnknownInputParams; } | { pathname: `/shelter`; params?: Router.UnknownInputParams; } | { pathname: `/water-rescue`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/community` | `/community`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-requests` | `/my-requests`; params?: Router.UnknownInputParams; };
    }
  }
}
